# ==============================================================================
# AMQCLI Configuration
# ==============================================================================
refresh_interval: 1s
encoding: utf-8

environments:
  dev:
    protocol: "stomp"  # or "amqp"
    host: "${MQ_HOST:-127.0.0.1}"
    stomp_port: "61613" # optional (default: 61613)
    web_port: "8161"    # optional (default: 8161)
    username: "${MQ_USER:-admin}"
    password: "${MQ_PASS:-admin}"
    readonly: false
  prod:
    protocol: "amqp"
    host: "10.0.0.5"
    amqp_port: "5672"   # optional (default: 5672)
    web_port: "8161"    # optional (default: 8161)
    username: "admin"
    password: "prod-password"
    readonly: true
